### ISSUE TITLE
Add old bubble chat

### ISSUE THREAD

**Issue by digidalstudios** [digidalstudios/TCS-disguised-as-Legacy-Chat#5]
Making something look like Legacy Chat without adding an old bubble chat option? Seems very wrong.

**Comment by digidal** [comment]
This is in the works. Unfinished files are in [Commit 68cfb60](https://github.com/digidalstudios/TCS-disguised-as-Legacy-Chat/commit/68cfb60a50eff4deaf63ed9e649e30c688f6b4a9).

**Comment by digidal** [comment]
Seems to be working. Would need more people to try and find bugs.

**Comment by digidal** [comment]
It seems like it's working. You can't see it when you're far away, but I assume that's normal.
